# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shaoshuai/vp_proj/rvp_ocx_vcml/rvp-ocx

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shaoshuai/vp_proj/rvp_ocx_vcml/rvp-ocx/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shaoshuai/vp_proj/rvp_ocx_vcml/rvp-ocx/build/CMakeFiles /home/shaoshuai/vp_proj/rvp_ocx_vcml/rvp-ocx/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shaoshuai/vp_proj/rvp_ocx_vcml/rvp-ocx/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named avp64

# Build rule for target.
avp64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 avp64
.PHONY : avp64

# fast build rule for target.
avp64/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avp64.dir/build.make CMakeFiles/avp64.dir/build
.PHONY : avp64/fast

#=============================================================================
# Target rules for targets named avp64-runner

# Build rule for target.
avp64-runner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 avp64-runner
.PHONY : avp64-runner

# fast build rule for target.
avp64-runner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avp64-runner.dir/build.make CMakeFiles/avp64-runner.dir/build
.PHONY : avp64-runner/fast

#=============================================================================
# Target rules for targets named vcml

# Build rule for target.
vcml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vcml
.PHONY : vcml

# fast build rule for target.
vcml/fast:
	$(MAKE) $(MAKESILENT) -f vcml/CMakeFiles/vcml.dir/build.make vcml/CMakeFiles/vcml.dir/build
.PHONY : vcml/fast

#=============================================================================
# Target rules for targets named mwr

# Build rule for target.
mwr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mwr
.PHONY : mwr

# fast build rule for target.
mwr/fast:
	$(MAKE) $(MAKESILENT) -f vcml/mwr/CMakeFiles/mwr.dir/build.make vcml/mwr/CMakeFiles/mwr.dir/build
.PHONY : mwr/fast

#=============================================================================
# Target rules for targets named systemc

# Build rule for target.
systemc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 systemc
.PHONY : systemc

# fast build rule for target.
systemc/fast:
	$(MAKE) $(MAKESILENT) -f vcml/systemc/src/CMakeFiles/systemc.dir/build.make vcml/systemc/src/CMakeFiles/systemc.dir/build
.PHONY : systemc/fast

#=============================================================================
# Target rules for targets named vcml-tapctl

# Build rule for target.
vcml-tapctl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vcml-tapctl
.PHONY : vcml-tapctl

# fast build rule for target.
vcml-tapctl/fast:
	$(MAKE) $(MAKESILENT) -f vcml/utils/CMakeFiles/vcml-tapctl.dir/build.make vcml/utils/CMakeFiles/vcml-tapctl.dir/build
.PHONY : vcml-tapctl/fast

#=============================================================================
# Target rules for targets named ocx-qemu-arm

# Build rule for target.
ocx-qemu-arm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ocx-qemu-arm
.PHONY : ocx-qemu-arm

# fast build rule for target.
ocx-qemu-arm/fast:
	$(MAKE) $(MAKESILENT) -f ocx-qemu-arm/CMakeFiles/ocx-qemu-arm.dir/build.make ocx-qemu-arm/CMakeFiles/ocx-qemu-arm.dir/build
.PHONY : ocx-qemu-arm/fast

#=============================================================================
# Target rules for targets named unicorn-build

# Build rule for target.
unicorn-build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unicorn-build
.PHONY : unicorn-build

# fast build rule for target.
unicorn-build/fast:
	$(MAKE) $(MAKESILENT) -f ocx-qemu-arm/CMakeFiles/unicorn-build.dir/build.make ocx-qemu-arm/CMakeFiles/unicorn-build.dir/build
.PHONY : unicorn-build/fast

#=============================================================================
# Target rules for targets named capstone

# Build rule for target.
capstone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 capstone
.PHONY : capstone

# fast build rule for target.
capstone/fast:
	$(MAKE) $(MAKESILENT) -f ocx-qemu-arm/capstone/CMakeFiles/capstone.dir/build.make ocx-qemu-arm/capstone/CMakeFiles/capstone.dir/build
.PHONY : capstone/fast

#=============================================================================
# Target rules for targets named capstone-static

# Build rule for target.
capstone-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 capstone-static
.PHONY : capstone-static

# fast build rule for target.
capstone-static/fast:
	$(MAKE) $(MAKESILENT) -f ocx-qemu-arm/capstone/CMakeFiles/capstone-static.dir/build.make ocx-qemu-arm/capstone/CMakeFiles/capstone-static.dir/build
.PHONY : capstone-static/fast

#=============================================================================
# Target rules for targets named ocx-runner

# Build rule for target.
ocx-runner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ocx-runner
.PHONY : ocx-runner

# fast build rule for target.
ocx-runner/fast:
	$(MAKE) $(MAKESILENT) -f ocx-qemu-arm/ocx/CMakeFiles/ocx-runner.dir/build.make ocx-qemu-arm/ocx/CMakeFiles/ocx-runner.dir/build
.PHONY : ocx-runner/fast

#=============================================================================
# Target rules for targets named ocx-test-runner

# Build rule for target.
ocx-test-runner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ocx-test-runner
.PHONY : ocx-test-runner

# fast build rule for target.
ocx-test-runner/fast:
	$(MAKE) $(MAKESILENT) -f ocx-qemu-arm/ocx/CMakeFiles/ocx-test-runner.dir/build.make ocx-qemu-arm/ocx/CMakeFiles/ocx-test-runner.dir/build
.PHONY : ocx-test-runner/fast

#=============================================================================
# Target rules for targets named ocx-dummy-core

# Build rule for target.
ocx-dummy-core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ocx-dummy-core
.PHONY : ocx-dummy-core

# fast build rule for target.
ocx-dummy-core/fast:
	$(MAKE) $(MAKESILENT) -f ocx-qemu-arm/ocx/CMakeFiles/ocx-dummy-core.dir/build.make ocx-qemu-arm/ocx/CMakeFiles/ocx-dummy-core.dir/build
.PHONY : ocx-dummy-core/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f ocx-qemu-arm/ocx/googletest/googlemock/CMakeFiles/gmock.dir/build.make ocx-qemu-arm/ocx/googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f ocx-qemu-arm/ocx/googletest/googlemock/CMakeFiles/gmock_main.dir/build.make ocx-qemu-arm/ocx/googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f ocx-qemu-arm/ocx/googletest/googletest/CMakeFiles/gtest.dir/build.make ocx-qemu-arm/ocx/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f ocx-qemu-arm/ocx/googletest/googletest/CMakeFiles/gtest_main.dir/build.make ocx-qemu-arm/ocx/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named test_main

# Build rule for target.
test_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_main
.PHONY : test_main

# fast build rule for target.
test_main/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_main.dir/build.make tests/CMakeFiles/test_main.dir/build
.PHONY : test_main/fast

#=============================================================================
# Target rules for targets named arm64_core_test

# Build rule for target.
arm64_core_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arm64_core_test
.PHONY : arm64_core_test

# fast build rule for target.
arm64_core_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/arm64_core_test.dir/build.make tests/CMakeFiles/arm64_core_test.dir/build
.PHONY : arm64_core_test/fast

src/avp64/core.o: src/avp64/core.cpp.o
.PHONY : src/avp64/core.o

# target to build an object file
src/avp64/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avp64.dir/build.make CMakeFiles/avp64.dir/src/avp64/core.cpp.o
.PHONY : src/avp64/core.cpp.o

src/avp64/core.i: src/avp64/core.cpp.i
.PHONY : src/avp64/core.i

# target to preprocess a source file
src/avp64/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avp64.dir/build.make CMakeFiles/avp64.dir/src/avp64/core.cpp.i
.PHONY : src/avp64/core.cpp.i

src/avp64/core.s: src/avp64/core.cpp.s
.PHONY : src/avp64/core.s

# target to generate assembly for a file
src/avp64/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avp64.dir/build.make CMakeFiles/avp64.dir/src/avp64/core.cpp.s
.PHONY : src/avp64/core.cpp.s

src/avp64/cpu.o: src/avp64/cpu.cpp.o
.PHONY : src/avp64/cpu.o

# target to build an object file
src/avp64/cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avp64.dir/build.make CMakeFiles/avp64.dir/src/avp64/cpu.cpp.o
.PHONY : src/avp64/cpu.cpp.o

src/avp64/cpu.i: src/avp64/cpu.cpp.i
.PHONY : src/avp64/cpu.i

# target to preprocess a source file
src/avp64/cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avp64.dir/build.make CMakeFiles/avp64.dir/src/avp64/cpu.cpp.i
.PHONY : src/avp64/cpu.cpp.i

src/avp64/cpu.s: src/avp64/cpu.cpp.s
.PHONY : src/avp64/cpu.s

# target to generate assembly for a file
src/avp64/cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avp64.dir/build.make CMakeFiles/avp64.dir/src/avp64/cpu.cpp.s
.PHONY : src/avp64/cpu.cpp.s

src/avp64/main.o: src/avp64/main.cpp.o
.PHONY : src/avp64/main.o

# target to build an object file
src/avp64/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avp64-runner.dir/build.make CMakeFiles/avp64-runner.dir/src/avp64/main.cpp.o
.PHONY : src/avp64/main.cpp.o

src/avp64/main.i: src/avp64/main.cpp.i
.PHONY : src/avp64/main.i

# target to preprocess a source file
src/avp64/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avp64-runner.dir/build.make CMakeFiles/avp64-runner.dir/src/avp64/main.cpp.i
.PHONY : src/avp64/main.cpp.i

src/avp64/main.s: src/avp64/main.cpp.s
.PHONY : src/avp64/main.s

# target to generate assembly for a file
src/avp64/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avp64-runner.dir/build.make CMakeFiles/avp64-runner.dir/src/avp64/main.cpp.s
.PHONY : src/avp64/main.cpp.s

src/avp64/system.o: src/avp64/system.cpp.o
.PHONY : src/avp64/system.o

# target to build an object file
src/avp64/system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avp64-runner.dir/build.make CMakeFiles/avp64-runner.dir/src/avp64/system.cpp.o
.PHONY : src/avp64/system.cpp.o

src/avp64/system.i: src/avp64/system.cpp.i
.PHONY : src/avp64/system.i

# target to preprocess a source file
src/avp64/system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avp64-runner.dir/build.make CMakeFiles/avp64-runner.dir/src/avp64/system.cpp.i
.PHONY : src/avp64/system.cpp.i

src/avp64/system.s: src/avp64/system.cpp.s
.PHONY : src/avp64/system.s

# target to generate assembly for a file
src/avp64/system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avp64-runner.dir/build.make CMakeFiles/avp64-runner.dir/src/avp64/system.cpp.s
.PHONY : src/avp64/system.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... unicorn-build"
	@echo "... arm64_core_test"
	@echo "... avp64"
	@echo "... avp64-runner"
	@echo "... capstone"
	@echo "... capstone-static"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... mwr"
	@echo "... ocx-dummy-core"
	@echo "... ocx-qemu-arm"
	@echo "... ocx-runner"
	@echo "... ocx-test-runner"
	@echo "... systemc"
	@echo "... test_main"
	@echo "... vcml"
	@echo "... vcml-tapctl"
	@echo "... src/avp64/core.o"
	@echo "... src/avp64/core.i"
	@echo "... src/avp64/core.s"
	@echo "... src/avp64/cpu.o"
	@echo "... src/avp64/cpu.i"
	@echo "... src/avp64/cpu.s"
	@echo "... src/avp64/main.o"
	@echo "... src/avp64/main.i"
	@echo "... src/avp64/main.s"
	@echo "... src/avp64/system.o"
	@echo "... src/avp64/system.i"
	@echo "... src/avp64/system.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

